#!/usr/bin/env sh
#MISE description="Build Hugo site via Dagger"
#MISE depends=["clean"]

set -e
exec dagger call build ${HUGO_BASEURL:+--base-url="$HUGO_BASEURL"} export --path="$MISE_PROJECT_ROOT/dist"
